
class InputFile():
    pass

"""
*Heading
** Job name: UserMat-Job Model name: Model-1
** Generated by: Abaqus/CAE 2017
*Preprint, echo=NO, model=NO, history=NO, contact=NO
**
** PARTS
**
*Part, name=Lochscheibe
*Node
      1,  -10.6066017,  -10.6066017,          10.

   6168,  -26.9230766,    20.833334,           8.
*Element, type=C3D8
  1,    1,   53,  721,   70,   95,  821, 3289,  761

*Nset, nset=Set-6, generate
    1,  6168,     1
*Elset, elset=Set-6, generate
    1,  4780,     1
** Section: Section-1
*Solid Section, elset=Set-6, material=Material-1
,
*End Part
**
** ASSEMBLY
**
*Assembly, name=Assembly
**
*Instance, name=Lochscheibe-1, part=Lochscheibe
*End Instance
**
*Nset, nset=_PickedSet19, internal, instance=Lochscheibe-1
 52,
*End Assembly
**
** MATERIALS
**
*Material, name=Material-1
*User Material, constants=2
210000., 0.3
**
** BOUNDARY CONDITIONS
**
** Name: x0 Type: Displacement/Rotation
*Boundary
_PickedSet17, 1, 1
** Name: yz0 Type: Displacement/Rotation
*Boundary
_PickedSet18, 2, 2
_PickedSet18, 3, 3
** Name: z0 Type: Displacement/Rotation
*Boundary
_PickedSet19, 3, 3
** ----------------------------------------------------------------
**
** STEP: Zugbelastung
**
*Step, name=Zugbelastung, nlgeom=NO
*Static
1., 1., 1e-05, 1.
**
** BOUNDARY CONDITIONS
**
** Name: Verschiebung Type: Displacement/Rotation
*Boundary
_PickedSet16, 1, 1, 0.5
**
** OUTPUT REQUESTS
**
*Restart, write, frequency=0
*Print, solve=NO
**
** FIELD OUTPUT: F-Output-1
**
*Output, field
*Node Output
U,
*Element Output, directions=YES
E, S
**
** HISTORY OUTPUT: H-Output-1
**
*Output, history, variable=PRESELECT
*End Step
"""

from compas_fea2.backends._core import Writer

Writer.write_heading()

Writer.write_nodes()
writer.write_node_sets()
writer.write_boundary_conditions()
writer.write_materials()
writer.write_elements()
writer.write_element_sets()
writer.write_steps()
